### ISSUE TITLE
Feed doesnt load

### ISSUE THREAD

**Issue by gabuum** [jsanahuja/jquery.instagramFeed#101]
Hi! 
thx for this wonderful skript! it worked super nice and fine till today! could it be possible that instagram changed something? It doesn't fetch the post by username... i tried the index.html from the package... just the content example 'by tag' works...

i hope you can help me! 
thank you very much
manu

**Comment by bullerouge** [comment]
Hi me too, 
Since yesterday, Instagram doesn't work live like that anymore : https://www.instagram.com/xxxxx/, it redirects to https://www.instagram.com/accounts/login/?next=/xxxxx/. 
Basically, i think, Instagram doesn't make any more public page.

Knowing that the script uses the public url... hoping that the devs can find an alternative.
It's a big problem for me too.
I try to find an alternative.

**Comment by mahotilo** [comment]
I do not clearly understand your problem because there is no such problem on my side. 

1. Does  the [script demo](https://www.sowecms.com/demos/jquery.instagramFeed/index.html)  work for you?

2. Have you tried to adjust `host` parameter of script?
> **host**
> String [url] 
> `https://www.instagram.com/ `
> URL where to fetch the data. Useful if instagram changes CORS policy
 
3. Are you participating in any "new/next interface" program of IG? For me, your link with `com/accounts/login/?next=/xxxxx/` is redirected to `.com/xxxxx/`.

**Comment by mahotilo** [comment]
Well, now I can see the same problem. 
Despite the new caching approach, I am steel able to catch "It looks like YOUR network has been temporary banned" error.

**Comment by wearekoala** [comment]
We have also found that this Instagram feed has stopped working, as of today.  Will keep an eye on this thread for updates.  Fingers crossed for a solution.

**Comment by rudel79** [comment]
also for me the same error: InstagramFeed.min.js.xhtml?ln=public/js:1 Instagram Feed: It looks like YOUR network has been temporary banned because of too many requests. wait for update. thank you

**Comment by pabrul** [comment]
The same error is happening to me, this message appears on the console
![image](https://user-images.githubusercontent.com/55573363/104051284-ad6e6600-51c6-11eb-8248-5b44857c7591.png)

**Comment by pabrul** [comment]
![image](https://user-images.githubusercontent.com/55573363/104054959-c24df800-51cc-11eb-9aac-b505b131f616.png)

**Comment by artcoholic** [comment]
I get the same error as pabrul.

**Comment by kamrowsky** [comment]
@pabrul  Same here

**Comment by mahotilo** [comment]
Well, I have just checked. I am unbanned now after more than 48 h. So, we need to increase the caching period. Maybe to 3-6 h.

**Comment by pabrul** [comment]
The error continues, it remains very unstable for me
![image](https://user-images.githubusercontent.com/55573363/104216017-4a740d80-5418-11eb-864e-dc8efded31d0.png)

**Comment by mahotilo** [comment]
@pabrul 
Are you using the latest version 2.0.0?

**Comment by m0nclous** [comment]
@pabrul
The script takes IG data from the cache (localStorage) if this error is catched. The cache will be updated after temp ban.
If you don't see images, then you didn't have cached data before the temporary ban.
This could be if you are viewing the page in incognito or another browser.

**Comment by Remling97** [comment]
I dont think the cache fixes the problem. If i look at the examples page only the one where it goes by tags work. The others dont. 
So this is an issue with instagram redirecting all requests if you are not logged in and most likely has nothing to do with them banning you for 24h.

**Comment by mahotilo** [comment]
Well, I have just caught a ban again right after looking at the example page.
Today during 6 hours, I have already done 3 reloads of my test page with the script in private/incognito mode (no cache). So the question is, do we have a request rate limit (request per hour) or a max reloads per day (24 h) limit (no mater how frequently)?

And my previous ban lasted more than 24 h. It seems to me, it took at least 48 h.

**Comment by mahotilo** [comment]
@Remling97 

> So this is an issue with instagram redirecting all requests if you are not logged in and most likely has nothing to do with them banning you for 24h.

When I am not in a ban, the script works perfectly for me regardless of whether I am logged in or not.

**Comment by jsanahuja** [comment]
> Well, I have just checked. I am unbanned now after more than 48 h. So, we need to increase the caching period. Maybe to 3-6 h.
> 
> UPD
> I was wrong when I was suggesting 1 h. It looks like IG changes its mind about the allowable frequency of ajax get() depending on the site load.

We will set the default `cache_time` to 6 hours. Either way, you guys can change that option as you wish.

**Comment by Federico-Iglesias** [comment]
@jsanahuja how are you? Did it worked changing the cache_time to 6 hours?

**Comment by jsanahuja** [comment]
I am not being banned but it always depends on the use each one gives to this library. Each use case has different requirements so if 6 hours is not enough (or too much) simply change as you need
