### ISSUE TITLE
Trouble Implementing Instagram Feed 1.5.4 

### ISSUE THREAD

**Issue by kenreeser** [jsanahuja/jquery.instagramFeed#106]
I recently downloaded and implemented version 1.5.4 of your Instagram Feed script and having trouble getting it work. Below is a screenshot of the console errors and just below is my implementation code:

Script:
<script src="js/InstagramFeed.min.js"></script>
		
		<script>
			(function(){
				new InstagramFeed({
					'username': 'mickeygillcreative',
					'container': document.getElementById("instagram-feed"),
					'display_profile': false,
					'display_biography': false,
					'display_gallery': true,
					'display_captions': false,
					'callback': null,
					'styling': true,
					'items': 8,
					'items_per_row': 4,
					'margin': 1,
					'image_size': 480,
					'lazy_load': true,
            		'on_error': console.error
				});
			})();
		</script>

![image](https://user-images.githubusercontent.com/13957237/105755064-cbeb9580-5f18-11eb-86e2-7c4fd8413910.png)

**Comment by m0nclous** [comment]
Check this https://github.com/jsanahuja/jquery.instagramFeed/issues/103#issuecomment-762488150
And https://github.com/jsanahuja/jquery.instagramFeed/issues/103#issuecomment-767053903

**Comment by mahotilo** [comment]
1. The current version is 2.0.1, yours is outdated.
2. According to the [documentation](https://www.sowecms.com/demos/jquery.instagramFeed/index.html), your line
`'container': document.getElementById("instagram-feed"),`
should look like
`'container': "#instagram-feed",`
3. You can read more about the error in the console and find a solution here https://github.com/jsanahuja/jquery.instagramFeed/issues/103

**Comment by kenreeser** [comment]
Thanks very much for your assistance and info.

**Comment by kenreeser** [comment]
@mahotilo 
Where can I download the 2.0.1 vanilla javascript version?

**Comment by kenreeser** [comment]
@mahotilo 
Never mind, silly question, I found the link. Thx again.

**Comment by m0nclous** [comment]
> Где я могу скачать ванильную версию javascript 2.0.1?

https://github.com/jsanahuja/InstagramFeed
Note: latest vanilla version `1.5.4` and the caching feature is not implemented in this plugin at this time.

**Comment by mahotilo** [comment]
Well, this repository is a jQuery version. So my answer is not correct for a vanilla JavaScript version. But the comments from https://github.com/jsanahuja/jquery.instagramFeed/issues/106#issuecomment-767064285 are relevant for a vanilla JavaScript version too.

**Comment by kenreeser** [comment]
Well, I stand corrected: the vanilla version I had was actually 1.4.0. I got the 1.5.4 from the package.json file.

**Comment by kenreeser** [comment]
Upon examining the unminified InstagramFeed.js file, it reads version 1.4.0.
