### ISSUE TITLE
change caption styling?

### ISSUE THREAD

**Issue by twiddly** [jsanahuja/jquery.instagramFeed#108]
I like the built-in styling but would like to change the font size of the caption (on hover).
Is there a way to do that?

**Comment by mahotilo** [comment]
Look at Example6
https://www.sowecms.com/demos/jquery.instagramFeed/index.html

**Comment by cube-dan** [comment]
’sup  @twiddly ... the PR hasn't been reviewed by the authors yet, but you can take a look at a potential solution in [PR#53](https://github.com/jsanahuja/InstagramFeed/pull/53)

**Comment by jsanahuja** [comment]
> I like the built-in styling but would like to change the font size of the caption (on hover).
> Is there a way to do that?

If you want to keep the other default styles you can simply add the following styles in your CSS:
```
a[data-caption]:hover::after{
  font-size: 1rem;
}
```

**Comment by cube-dan** [comment]
Thanks for the tip Javier. Would you guys mind adding [your tip](https://github.com/jsanahuja/jquery.instagramFeed/issues/108#issuecomment-783497554) to [the manual](https://www.sowecms.com/demos/InstagramFeed/)?

**Comment by jsanahuja** [comment]
> Thanks for the tip Javier. Would you guys mind adding [your tip](https://github.com/jsanahuja/jquery.instagramFeed/issues/108#issuecomment-783497554) to [the manual](https://www.sowecms.com/demos/InstagramFeed/)?

Hmm where would you add it?

**Comment by cube-dan** [comment]
I'm thinking as part of the "styling" attribute. Currently:
```
styling | Boolean | true | Enables default inline CSS styles
````
... would maybe read: 
```
styling | Boolean | true | Enables default inline CSS styles. You can use the a[data-caption]:hover::after selector to add your own styles. Example: a[data-caption]:hover::after{ font-size: 1rem; } to set the font size of all the captions.
```
