### ISSUE TITLE
Add location feed?

### ISSUE THREAD

**Issue by titken** [jsanahuja/jquery.instagramFeed#109]
Would it be possible to add functionality, to show images from a given location, for example:

https://www.instagram.com/explore/locations/237205415/det-kolde-gys/
or
https://www.instagram.com/explore/locations/990978382/la-banchina/

I'm using "tags" and it works like a charm :)

**Comment by mahotilo** [comment]
Could you try a username, e.g. 'explore/locations/237205415/det-kolde-gys/', as a temporary trick?

**Comment by titken** [comment]
> 
> 
> Could you try a username, e.g. 'explore/locations/237205415/det-kolde-gys/', as a temporary trick?

Unfortunately not - Also tried to increase cache_time parm. I get this error in the console while loading.

Instagram Feed: Your network has been temporary banned by Instagram because of too many requests. Consider increasing your 'cache_time'. See https://github.com/jsanahuja/jquery.instagramFeed/issues/25 and https://github.com/jsanahuja/jquery.instagramFeed/issues/101 4

**Comment by mahotilo** [comment]
@titken 
Could you try this set of parameters including a newly discovered workaround for the CORS problem?

'host': 'https://images' + ~~(Math.random() * 3333) + '-focus-opensocial.googleusercontent.com/gadgets/proxy?container=none&url=https://www.instagram.com/',
'username': 'explore/locations/237205415/det-kolde-gys/'

It seems to me you might get what you asked for.

**Comment by jsanahuja** [comment]
It is not age restricted but the response is unexpected and that is what we used to understand when that happens. It will be available in the 3.0.0 release

**Comment by jsanahuja** [comment]
@titken should work with [3.0.0](https://github.com/jsanahuja/jquery.instagramFeed/releases/tag/3.0.0) release with:
```
  'host': 'https://images' + ~~(Math.random() * 3333) + '-focus-opensocial.googleusercontent.com/gadgets/proxy?container=none&url=https://www.instagram.com/',
  'location': '237205415/det-kolde-gys'
```

**Comment by titken** [comment]
Thank you very much for the feature! I can confirm it is working as expected and I updated the JS-code on my site.
Don't quite understand the Google proxy-"hack", but nice fix :)
