### ISSUE TITLE
InstagramFeed: It looks like YOUR network has been temporary banned because of too many requests

### ISSUE THREAD

**Issue by davidhayes03** [jsanahuja/jquery.instagramFeed#110]
Is there a fix for this?

**Comment by mahotilo** [comment]
Actually, it is not an issue to report. This is a message from the script describing the situation. Wait for the end of your ban. It can take1-2 days. 
If you want, you can find more info about the problem and joint the discussion in the previous issue https://github.com/jsanahuja/jquery.instagramFeed/issues/103.
