### ISSUE TITLE
It is blocked by CORS policy

### ISSUE THREAD

**Issue by j-dipierro** [jsanahuja/jquery.instagramFeed#111]
Hello everyone,

My website recently stopped loading instagram feed with Cross Origin error:

"Access to XMLHttpRequest at '(my-websiteurl)' from origin '(my-websiteurl)' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

Unfortunately, my website use VTEX store which don't allow me to manage Cross Origin headers, or better said, is a "Software as a service".

Host is defined as 'https://www.instagram.com' and even this way I'm getting CORS error.

What can I do?

Thanks in advance.

**Comment by Mikhail-MM** [comment]
I'm seeing a CORS error intermittently as well - we just upgraded to version 2.0.2 to fix the Rate Limiting issue, I believe recently the repo was PR'd with a fix that created a 6 hour LocalStorage cache. 

Several hours ago I tested refreshing the page many times and it seemed the cache was working, no longer getting a rate limit.

Now getting a CORS error, that disappeared when I switched browsers. Might be an on and off issue?

**Comment by j-dipierro** [comment]
Yes. It can be an on and off issue. But I googled about it a bit, and people are saying that IG implemented new CORS policy on some of their servers and it's causing this intermittence. I don't know if some cache management will work, as instagramFeed loads intermittently. I downloaded the source code to take a look as well.

**Comment by jsanahuja** [comment]
See https://github.com/jsanahuja/jquery.instagramFeed/issues/103#issuecomment-784362740

**Comment by Mikhail-MM** [comment]
@jsanahuja Thank you for the update and than you for continuing to support this project!

**Comment by jsanahuja** [comment]
Release 2.1.0 implementing GraphQL (with `user_id` parameter) is ready. We have also implemented request retries (limited by `max_tries` parameter) to avoid arbitrary CORS errors.
