### ISSUE TITLE
Which files are required?

### ISSUE THREAD

**Issue by Morecoffee** [jsanahuja/jquery.instagramFeed#112]
I have got the script working, thank you.  I am wondering though which files I need to have on the server?  It is working now with just 'jquery.instagramFeed.min.js' do I need any of the other ones.  I want to be sure the cache part is working as I was banned once already. I did ad the cache_time option to my html file.  Thanks

**Comment by mahotilo** [comment]
As far as functionality is concerned, 'jquery.instagramFeed.min.js' is enough. Moreover, you can only use the script from CDN https://cdnjs.com/libraries/jquery.instagramFeed.  For distribution and modification, please read the Licence.
