### ISSUE TITLE
"Access to XMLHttpRequest has been blocked by CORS policy"

### ISSUE THREAD

**Issue by gbvaz** [jsanahuja/jquery.instagramFeed#113]
Hi, 

I'm getting the following error while trying to load it:

`Access to XMLHttpRequest has been blocked by CORS policy No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I'm using the most recent version available as of today (2.1.1). Am I missing something? 

Thanks for your help!

**Comment by politeshrimp** [comment]
Can this be fixed by using CORS proxy server?
[https://github.com/Rob--W/cors-anywhere/](https://github.com/Rob--W/cors-anywhere/)

**Comment by HeartexceL** [comment]
No you're not missing something. The latest version with CORS policy error fix  stopped working yesterday at least on me.
seems like looping the request callback for a number of times aren't working anymore.

**Comment by Anmartawfik** [comment]
Same for me CORS issue appeared yesterday.

**Comment by clestcruz** [comment]
I'm also having this issue at the moment, anyone have a fixed yet?

**Comment by lothar75** [comment]
Same issue here. Projects with this plugin are not showing the Instagram feed anymore because of the CORS issue.

**Comment by mahotilo** [comment]
@politeshrimp 

> CORS Anywhere is a **NodeJS** proxy which adds CORS headers to the proxied request.

Please have a look at this working solution
https://github.com/jsanahuja/jquery.instagramFeed/issues/103#issuecomment-788260968

**Comment by introzen** [comment]
> @politeshrimp
> 
> > CORS Anywhere is a **NodeJS** proxy which adds CORS headers to the proxied request.
> 
> Please have a look at this working solution
> [#103 (comment)](https://github.com/jsanahuja/jquery.instagramFeed/issues/103#issuecomment-788260968)

That solution appears to be broken now unfortunately.

**Comment by mahotilo** [comment]
Yes I have had the same problem already, but it goes away in a minute.
With a cache it makes its work.

**Comment by introzen** [comment]
> Yes I have had the same problem already, but it goes away in a minute.
> With a cache it makes its work.

Indeed it is now working again. Problem seems to be intermittent, though, so _permanent fix_? Sadly, no.

**Comment by politeshrimp** [comment]
> @politeshrimp
> 
> > CORS Anywhere is a **NodeJS** proxy which adds CORS headers to the proxied request.
> 
> Please have a look at this working solution
> [#103 (comment)](https://github.com/jsanahuja/jquery.instagramFeed/issues/103#issuecomment-788260968)

It stopped working for me unfortunately
![image](https://user-images.githubusercontent.com/47284416/109654031-64091a00-7b6a-11eb-8282-b8bb0481aea6.png)

**Comment by jamessaget** [comment]
Not working here either just retrying x5 times with the same response

**Comment by mahotilo** [comment]
@jamessaget 
Literally, wait a minute.

**Comment by jsanahuja** [comment]
Upgrade to [3.0.0](https://github.com/jsanahuja/jquery.instagramFeed/releases/tag/3.0.0) and use this https://github.com/jsanahuja/jquery.instagramFeed/issues/103#issuecomment-788260968
