### ISSUE TITLE
Latest Default Files Not Working

### ISSUE THREAD

**Issue by politeshrimp** [jsanahuja/jquery.instagramFeed#117]
I have downloaded the latest files but I can't get it to work at all. I get the same CORS error. I've been using this script since 2018 but now I can't even get the default files (index.html) loading Instagram images.
![image](https://user-images.githubusercontent.com/47284416/109709506-44431780-7ba5-11eb-8d8f-8ccb714e6e75.png)
![image](https://user-images.githubusercontent.com/47284416/109709612-6341a980-7ba5-11eb-8d1a-630b5881907d.png)

changing the host to `https://images' + ~~(Math.random() * 3333) + '-focus-opensocial.googleusercontent.com/gadgets/proxy?container=none&url=https://www.instagram.com/` doesn't solve the issue.

Please guide me if I'm doing anything wrong as I see the [documentation page](https://www.sowecms.com/demos/jquery.instagramFeed/index.html) loading some of the feeds, maybe it is cached or something but downloading the very same files on my machine will not load any feeds.

**Comment by mahotilo** [comment]
It seems tome, it does not work for a local server.

**Comment by politeshrimp** [comment]
> It seems to me, it (the google proxy) does not work for a local server.

Confirmed, it is blocked on localhost
Thanks for your help.
