### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Mahi-cgvak** [jsanahuja/jquery.instagramFeed#118]
Access to XMLHttpRequest at 'https://www.instagram.com/test/' from origin 'http://testdomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Any solution for this guys?

Also Is this possible to display likes and comments count for each post?

**Comment by mahotilo** [comment]
> Access to XMLHttpRequest at 'https://www.instagram.com/test/' from origin 'http://testdomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Any solution for this guys?

This  is not a problem, it is just an evidence of a fair attempt to load data directly form IG. When it fails, the script uses an alternative google proxy, and you are given with the results.

> Also Is this possible to display likes and comments count for each post?

Please, read this Issue https://github.com/jsanahuja/jquery.instagramFeed/issues/105

**Comment by Mahi-cgvak** [comment]
Thanks @mahotilo for your reply.
But I'm not getting any data from my Instagram. 
It just returns "Instagram Feed: Unable to fetch the given user/tag. Instagram responded with the status code: 0 5"

**Comment by mahotilo** [comment]
Are you using the latest version 3.0.0? It works for me.

**Comment by Mahi-cgvak** [comment]
Worked now!!!. Thanks for your help @mahotilo
