### ISSUE TITLE
Error "str.replace is not a function"

### ISSUE THREAD

**Issue by mahotilo** [jsanahuja/jquery.instagramFeed#120]
Continuing discussion of the new type of error https://github.com/jsanahuja/jquery.instagramFeed/issues/103#issuecomment-790524571

**Comment by mahotilo** [comment]
Can confirm, it works
@web-burn, what about your side?

**Comment by web-burn** [comment]
@mahotilo, yes, it works fine.

**Comment by unlockdesgn** [comment]
now it is not working :(
https://www.sowecms.com/demos/jquery.instagramFeed/index.html
