### ISSUE TITLE
Instagram Feed Stopped Displaying

### ISSUE THREAD

**Issue by perryworld** [jsanahuja/jquery.instagramFeed#123]
Hi,

New to GitHub
We have a site at pollingtonpreschool.com and display their Instagram feed on the site
Everything was working fine but in the last couple of days it stopped working and in the console we are getting this message

Access to XMLHttpRequest at 'https://www.instagram.com/explore/tags/pollingtonpreschoolweb/' from origin 'https://pollingtonpreschool.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is this something you can help with

Any help is much appreciated

Thanks
Rich

**Comment by mahotilo** [comment]
Have you updated the script to the latest version 3.0.2?

**Comment by perryworld** [comment]
Hi

Thanks for coming back so quick
We are new to GitHub - how do we upgrade to the latest version ;o(

Rich

**Comment by mahotilo** [comment]
Download it from https://github.com/jsanahuja/jquery.instagramFeed/releases/tag/3.0.2
and then replace jquery.instagramFeed.min.js on your site with the new one.

**Comment by perryworld** [comment]
Hi,

We've done that but still get the same error

Rich

**Comment by perryworld** [comment]
Sorry, you can se the issue here
https://pollingtonpreschool.com/gallery/pollington-social-media

**Comment by mahotilo** [comment]
No, as I can see you are not using the latest version.

**Comment by perryworld** [comment]
Hi,
We downloaded the zip and extracted it 
We then renamed the existing jquery.instagramFeed.min.js  to jquery.instagramFeed.min.jsOLD and uploaded the new one
Not sure why it's still picking up the old one
Cheers
Rich

**Comment by perryworld** [comment]
Hi,
Any other ideas as we updated the file but it didn't seem to make any difference
Any help would really be appreciated
Cheers
Rich

**Comment by mahotilo** [comment]
- Open the console, find the error, click on the script name.

![image](https://user-images.githubusercontent.com/14929385/110205139-742d3c00-7e7f-11eb-9fb6-003e89609b80.png)

- Save the script from your site to your disk.

![image](https://user-images.githubusercontent.com/14929385/110205263-c1a9a900-7e7f-11eb-802b-51c456221096.png)

- Compare jquery.instagramFeed.min.js from your site and from the last release.

Are they the same? As of me, no.

**Comment by perryworld** [comment]
Hi mahotilo

Thanks for this - I have just tried this and they didn't match so I have deleted the file and uploaded it again
Following your instructions I compared the files and it now says they are the same
Unfortunately the Instagram images still don't show

cheers
Rich

**Comment by mahotilo** [comment]
> Following your instructions I compared the files and it now says they are the same

I can not confirm here. I see the old one.

**Comment by perryworld** [comment]
Hi mahotilo

Sorry for all the questions
I've just checked your file and it contains "location"
I checked the file on my server and that also contains "location" - I've attached my file
So I've no idea why you are seeing the old version - cache possibly - I have cleared it on my server

Thanks for your help with this - much appreciated

Cheers
Rich
[jquery.instagramFeed.min (3).zip](https://github.com/jsanahuja/jquery.instagramFeed/files/6095413/jquery.instagramFeed.min.3.zip)

**Comment by mahotilo** [comment]
You still have some kind of mess with your script file.
Your page uses this one
https://pollingtonpreschool.com/jquery.instagramFeed.min.js
It is old and does not contain "location". Please, check, how many instances of jquery.instagramFeed.min.js you have.
Or, switch to CDN
https://cdnjs.cloudflare.com/ajax/libs/jquery.instagramFeed/3.0.2/jquery.instagramFeed.min.js

**Comment by perryworld** [comment]
Please accept my apologies 
There was another version in the root  - I have replaced that one and now it is working

Thanks for the great support - much appreciated

Rich
