### ISSUE TITLE
TypeError: a.get is not a function

### ISSUE THREAD

**Issue by gigibotte** [jsanahuja/jquery.instagramFeed#125]
Hey :) 

Until few weeks ago everything was working fine. However now I get this error on my console. I'm using the last release 3.0.3
`jquery.instagramFeed.min.js:1 Uncaught TypeError: a.get is not a function`
`at g (jquery.instagramFeed.min.js:1)`
 `at h (jquery.instagramFeed.min.js:1)`
`at Function.a.instagramFeed (jquery.instagramFeed.min.js:1)`
`at home_minimal_footer.html:194`
`at dispatch (jquery-3.5.1.slim.min.js:2)`
at v.handle (jquery-3.5.1.slim.min.js:2)
`
could it be a problem with jquery? or any idea how to solve this?

Thanks a lot

**Comment by mahotilo** [comment]
Could you try using a non-minified version jquery.instagramFeed.js?

**Comment by gigibotte** [comment]
hi @mahotilo ! 
Same error also in this case
```
Uncaught TypeError: $.get is not a function
    at request_data (jquery.instagramFeed.js:149)
    at get_data (jquery.instagramFeed.js:194)
    at Function.$.instagramFeed (jquery.instagramFeed.js:397)
    at home_minimal_footer.html:225
    at dispatch (jquery-3.5.1.slim.min.js:2)
    at v.handle (jquery-3.5.1.slim.min.js:2)
```

this is the jquery I'm loading (if needed) 

   ` <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
`

**Comment by jsanahuja** [comment]
Please show the order you are loading JS files with all the parameters (defer, async, etc)

**Comment by gigibotte** [comment]
This is the order  I have the js files loaded
```
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src = "js/jquery.instagramFeed.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/bootstrap.min.js"></script>

    <script>
        (function($){
            $(window).on('load', function(){
                $.instagramFeed({
                    'username': 'briochehandmade',
                    'container': "#instagram-feed1",
                    'display_profile': false,
                    'display_biography': false,
                    'display_gallery': true,
                    'display_captions': true,
                    'callback': null,
                    'styling': true,
                    'items': 12,
                    'margin': 0.25
                });
            });
        })(jQuery);
    </script>
```
Thanks again for your help!

**Comment by mahotilo** [comment]
> $(window).on('load', function(){

should be 

$(document).ready(function() {

**Comment by jsanahuja** [comment]
>  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
>  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

Why are you loading both `jQuery` and `jQuery slim`? `jQuery slim` (which doesn't have `$.get`) is overriding `jQuery`

**Comment by jsanahuja** [comment]
Just in case, this doesn't either make sense:
```
    <script src="js/bootstrap.js"></script>
    <script src="js/bootstrap.min.js"></script>
```

**Comment by gigibotte** [comment]
Hey! thanks a lot to both of you! (also for suggestions on scripts that should be loaded) 

I am now not getting the error anymore (I'm getting the CORS one but I'm looking at previous issues to solve it)
Thanks again

**Comment by jsanahuja** [comment]
> Hey! thanks a lot to both of you! (also for suggestions on scripts that should be loaded)
> 
> I am now not getting the error anymore (I'm getting the CORS one but I'm looking at previous issues to solve it)
> Thanks again

Set the `host` param:
```
Recommended as Instagram is CORS restricted again:
'host: 'https://images' + ~~(Math.random() * 3333) + '-focus-opensocial.googleusercontent.com/gadgets/proxy?container=none&url=https://www.instagram.com/'
```

**Comment by gigibotte** [comment]
hey @jsanahuja Sorry for commenting again the thread. 

I still have the CORS issue both on my own project and on the index.html files of the repo. 
I added the the host parameter as suggested but is not working (tried several times this week).
Any suggestion?

Thanks a lot!

**Comment by Ivan0x9** [comment]
Hey everyone, I noticed the same issues happening. After adding the host parameter it worked fine. Few months later, on every site I added the host parameter now shows the same CORS error again.
Anyone figured out how to fix it?
