### ISSUE TITLE
blocked by CORS policy has ramped up

### ISSUE THREAD

**Issue by awasson** [jsanahuja/jquery.instagramFeed#127]
Javier, 
I'm not sure if Instagram is purposely causing trouble with acquiring remote instagram feeds but I've been watching the messages on my JS console and their changes to CORS policy have increased the number of JS "Instagram Feed: Request failed" errors dramatically. 

On Monday everything was fine but on Wednesday I noted that several installations of jquery.instagramFeed were reporting a single fail and then rendering the feed. Today, I am able to render the feed but all 8 attempts are reporting failure in my JS console. 

On a related note, I built and maintain the Drupal integration module for your JS library and there are currently some ~3000 installations so I am motivated to keep an eye on things. 

Cheers,
Andrew

**Comment by mahotilo** [comment]
It is Google. The problem is temporary. I have got it in one moment, but now everything is ok.

**Comment by awasson** [comment]
It's Google? I'm not sure that I understand how that's occurring but I do see that now some feeds that were showing 8 errors and not resolving are now showing with a single error and one is now showing with no errors.

Is there anything we can do to mitigate the issue?

Thanks,
Andrew

**Comment by mahotilo** [comment]
> Is there anything we can do to mitigate the issue?

I am afraid not. The current solution (several tries, alternative google proxy and caching) is the best we have.

**Comment by mahotilo** [comment]
`are` now showing with a single error and one is now showing with no errors.

You can reduce the number of errors in the console by changing the `host` parameter.
https://github.com/jsanahuja/jquery.instagramFeed/issues/125#issuecomment-792589859

**Comment by awasson** [comment]
Thanks for pointing out the `host` parameter. I hadn't seen that earlier. I'll give that a shot and see how it responds.

Cheers,
Andrew

**Comment by awasson** [comment]
@mahotilo, thanks for the tip about the `host` parameter. I believe that is the fix. I've updated my module to use it and it seems to have completely fixed it.

I'll close the issue.

Cheers,
Andrew

**Comment by jsanahuja** [comment]
The real workaround is proxying the request and use GraphQL (`user_id`` parameter)

**Comment by awasson** [comment]
Awesome! I'll have to do some R&D locally on this but that might be something I add to the Drupal module. There are some really great features in your library. It makes adding and configuring a feed a breeze. 

Thanks,
Andrew
