### ISSUE TITLE
Retrieving images from username with tags

### ISSUE THREAD

**Issue by userofit123** [jsanahuja/jquery.instagramFeed#22]
Is there a way to retrieve the images using both the "username" and "tag" options?

I want to get images with a specific tag from a specific user, but at the moment its one or the other.

**Comment by jsanahuja** [comment]
There is not.

As you might know, our library works fetching IG web results. So unless the search can be done via web, we can't do anything to implement it.

If you know a way to do it please let us know or just send your pull request
