### ISSUE TITLE
429 (Too many requests)

### ISSUE THREAD

**Issue by jongirard** [jsanahuja/jquery.instagramFeed#23]
Hi there,

Using this on a site and during development every 2 or 3 reloads I get an error of "429 (Too many requests) originating from "https://cors-anywhere.herokuapp.com/https://www.instagram.com/instagramuser". 

Is this a known problem with this workaround library and is there any resolution to this?

**Comment by jsanahuja** [comment]
That is a demo of a proxy implementation to bypass CORS. This is not needed anymore so you don't need to use it. Use the official instagram host instead
