### ISSUE TITLE
How to limit items when using get_data

### ISSUE THREAD

**Issue by nugrahaindie** [jsanahuja/jquery.instagramFeed#30]
`$.instagramFeed({
                    'tag': 'tag',
                    'get_data': true,
                    'items': 20, //it's won't work
                    'callback': function (data) {
                        console.log(data);
                    }
                });`

**Comment by csanahuja** [comment]
With `get_data` parameter the data its returned unprocessed to the callback function, limit does not apply. 

Once there is up to you how to process it. Iterate over the array of images and get the number you desire.

See example 7: https://www.sowecms.com/demos/jquery.instagramFeed/index.html#tabExamples

**Comment by mangcoding** [comment]
Ok Thanks, So i should limit by myself then.
Here is I implemented your script on my case

https://mangcoding.github.io/instagram-feeder/

Thanks for your awesome script

**Comment by jsanahuja** [comment]
Looks great!
