### ISSUE TITLE
More than 12

### ISSUE THREAD

**Issue by nikolassx** [jsanahuja/jquery.instagramFeed#31]
How can I show more than 12 posts?

**Comment by jsanahuja** [comment]
As long as we are loading the items from the instagram page, 12 is the maximum.

To load more Instagram uses a private API which is not CORS accessible.

If you really need to load more than 12 you will have to use an access token based library

**Comment by skullwritter** [comment]
Get the id from:
`https://www.instagram.com/web/search/topsearch/?query={username}`
object array - user - pk (the id)

get the feed info:
`https://www.instagram.com/graphql/query/?query_id=17888483320059182&id={user_id}&first={number of posts}&after=`
data - user - edge_owner_to_timeline_media (media) - edges {the media object array}
data - user - edge_owner_to_timeline_media (media) - page_info - has_next_page (if true use the cursor bellow to paginate)
data - user - edge_owner_to_timeline_media (media) - page_info - end_cursor (the end cursor for pagination)
get the feed info:
`https://www.instagram.com/graphql/query/?query_id=17888483320059182&id={user_id}&first={number of posts}&after={end_cursor}`
the query with the pagination
