### ISSUE TITLE
I can't get it to work.

### ISSUE THREAD

**Issue by valecd** [jsanahuja/jquery.instagramFeed#32]
Hi, maybe its not issue, but i can't get it to work.
I want to show small gallery. Can you show me working file? Or somewhere on web?
What am I doing wrong?
When i put js to file it will do nothing for a example my file looks like this:

`<html>
    <head>
          <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script type="text/javascript" src="jquery.instagramFeed.min.js"></script>
<script>
    (function($){
        $(window).on('load', function(){
            $.instagramFeed({
                'username': 'myname',
                'container': "#spring",
                'display_profile': true,
                'display_biography': true,
                'display_gallery': true,
                'callback': null,
                'styling': true,
                'items': 8,
                'items_per_row': 4,
                'margin': 1 
            });
        });
    })(jQuery);
</script>

    </head>
    <body>
        <div>Its working</div>
        <div id="jsonHere"></div>
    </body>
</html>`

**Comment by valecd** [comment]
OK i got it. The main issue is that firefox plugin to block fb outside blocked this showing instagram pictures, its weird because on wordpress it works well.

**Comment by jsanahuja** [comment]
Alright, I'll close the issue.
