### ISSUE TITLE
How to change alt tag shown in the instagram image  on website. Actually i don't like to show alt like this . When it shows in google search result it don't look good 

### ISSUE THREAD

**Issue by HarshilTyagi1993** [jsanahuja/jquery.instagramFeed#33]
Hi, I want to change alt text data and structure which can appear in the google search result. Current structure: username Instagram image 0 like this which does not look good anywhere. Please help.

**Comment by jsanahuja** [comment]
This is not possible yet. This would be a feature request so we will consider to implement this in a future release.

Also, the way we would implement it would be defining an alt tag pattern, so the result will be almost the same

**Comment by SDSUFowler** [comment]
Adding onto this thread, not having a usable Alt tag is an accessibility issue. A simple fix for this would be to at least use the image caption as the alt tag. So, the code for the alt tag would become:
`+"' alt='"+a[d].node.edge_media_to_caption.edges[0].node.text+"'"+`

**Comment by jsanahuja** [comment]
For images with only hashtags in the text that will be undefined. What I did is setting the caption in the following priority:
- image text
- image instagram alt
- {{tag/username}} image X

Thanks :)
