### ISSUE TITLE
CDN Access

### ISSUE THREAD

**Issue by glennyboy** [jsanahuja/jquery.instagramFeed#34]
Great script. Any chance of adding it to a CDN like https://cdnjs.com/ ?

Thanks

Glennyboy

**Comment by jsanahuja** [comment]
I would like to add it there too but the repository requires to have at least 200 stars to be added to that CDN:
>For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.
>
>The new library must have at least one officially public accessible repository and open source license.```

**Comment by glennyboy** [comment]
I've added my star. I must say I'm surprised it only has 76. I'll get the word out!

**Comment by jsanahuja** [comment]
Thank you! 😄

**Comment by AnTheMaker** [comment]
Any updates? It has more than 200 Stars now! 👍

**Comment by jsanahuja** [comment]
They accepted the pull request so should be available soon

**Comment by jsanahuja** [comment]
It is already available :D
https://cdnjs.com/libraries/jquery.instagramFeed
https://cdnjs.cloudflare.com/ajax/libs/jquery.instagramFeed/1.3.2/jquery.instagramFeed.min.js
https://cdnjs.cloudflare.com/ajax/libs/jquery.instagramFeed/1.3.2/jquery.instagramFeed.js

**Comment by AnTheMaker** [comment]
Awesome!

**Comment by glennyboy** [comment]
Great!

**Comment by jsanahuja** [comment]
Added a link to CDNJS in the documentation
