### ISSUE TITLE
Display description, comments and likes

### ISSUE THREAD

**Issue by marqmedia** [jsanahuja/jquery.instagramFeed#36]
Hi there, awesome script! Is there a way to display the post description within the image? Same for comments and likes. Thanks!

**Comment by jsanahuja** [comment]
There is no way to do that for now. The only approach would be getting the feed in JSON format using the `get_data` and `callback` options and displaying yourself.

That is only for description and likes. The data we get from instagram does not include comments. For that we would probably have to make an extra request and parse per image, so I think we won't be into adding that feature.

**Comment by mandras73** [comment]
> There is no way to do that for now. The only approach would be getting the feed in JSON format using the `get_data` and `callback` options and displaying yourself.
> 

Hi jsanahuja,
Can you please describe this a little bit more?
I just want to display the description of the post. 

                    'get_data': true,
                    'callback': null,

How can I configure the callback to display the text?
Thanks

**Comment by mandras73** [comment]
Here you can find an example, using by rss.app -> https://widget.rss.app/v1/wall.js

**Comment by jsanahuja** [comment]
It is all 

> > There is no way to do that for now. The only approach would be getting the feed in JSON format using the `get_data` and `callback` options and displaying yourself.
> 
> Hi jsanahuja,
> Can you please describe this a little bit more?
> I just want to display the description of the post.
> 
> ```
>                 'get_data': true,
>                 'callback': null,
> ```
> 
> How can I configure the callback to display the text?
> Thanks

Please see the 7th example in the docs

**Comment by mandras73** [comment]
Yes, but this is just the result payload, how can I use only the description displayed below the images

**Comment by jsanahuja** [comment]
There is no simple way (for now) to display descriptions below images. If you really want to do this you will have to find what you need in the result payload and build everything by yourself
