### ISSUE TITLE
Responsive "items_per_row" Value

### ISSUE THREAD

**Issue by surayashivji** [jsanahuja/jquery.instagramFeed#4]
Is there a way to change the "items_per_row" value in a media query? I'm trying to make items_per_row = 3 on desktop and items_per_row = 2 on mobile screens.

Thanks for the great repo!

**Comment by jsanahuja** [comment]
There is not but you can do that overriding css. For example:
```
@media only screen and (max-width:40em){
  .instagram_gallery img {
    width: 18% !important;
  }
}
```
If you don't like this way you can disable styling and apply your owns
```
			$.instagramFeed({
				...
				'styling': false,
				...
			});
```
Or get the raw json:
```
			$.instagramFeed({
				...
				'get_raw_json': true
				...
			});
```
