### ISSUE TITLE
Incorrect documentation for 'display_igtv'

### ISSUE THREAD

**Issue by BWPanda** [jsanahuja/jquery.instagramFeed#44]
The [options documentation](https://www.sowecms.com/demos/jquery.instagramFeed/index.html#options) for `display_igtv` says the default value is `true`, whereas it [appears](https://github.com/jsanahuja/jquery.instagramFeed/blob/master/jquery.instagramFeed.js#L21) to actually be `false`...

**Comment by jsanahuja** [comment]
Fixed, thanks for your feedback :)
