### ISSUE TITLE
Documentation for `items` not 100% correct

### ISSUE THREAD

**Issue by BWPanda** [jsanahuja/jquery.instagramFeed#46]
The [documentation](https://www.sowecms.com/demos/jquery.instagramFeed/index.html#options) for the `items` option states:

> Num of items to display in gallery. Accepted values [0-12]

However this limit is only true for users. Tags can have many more than 12 (at least 70 according to [Example 4](https://www.sowecms.com/demos/jquery.instagramFeed/index.html#examples)).

**Comment by jsanahuja** [comment]
Fixed, thanks for your feedback :)
