### ISSUE TITLE
Getting 302 redirection to login

### ISSUE THREAD

**Issue by KevinPesenti** [jsanahuja/jquery.instagramFeed#50]
Hi there ! I've set up the library on a project, works perfectly fine. However, after a few days, the feed stopped working. 

I was scrapping info from a single client instagram account to display their latest publications. Now I get 302 redirection through instagram login page, avoiding me to retrieve datas from public profile. 

From what I've read, Instagram of course has a limit for scrapping. Do you know if there is a way to bypass it, or any additional infos regarding actual limit?

**Comment by jsanahuja** [comment]
Please see #25 and #42
