### ISSUE TITLE
An error (Display breaks on "·" character) was introduced in latest Jan 7 2020

### ISSUE THREAD

**Issue by awasson** [jsanahuja/jquery.instagramFeed#52]
Hi There,
I've produced a Drupal module to integrate your library into Drupal sites and recently an issue came up where if an image on instagram contained a "·" character in the name of the image, it would break the display. 

I tracked down the issue to be something that was introduced between the November 29, 2019 version of jquery.instagramFeed.min.js and the one that was most recently released on January 7, 2020. 

If I use the January 7, 2020 version, the problem comes up. If I use the November 29, 2019 version, the problem doesn't exist. 

The instagram user I'm referring to is: transcend_the_physical

I've attached relevant screenshots. The issue is discussed here: https://www.drupal.org/project/simple_instagram_feed/issues/3111759

<img width="1016" alt="Screenshot 2020-02-11 12 26 03" src="https://user-images.githubusercontent.com/2935397/74372520-a14c0f80-4d8f-11ea-8d55-64a7cd7feda5.png">

I haven't run a diff to check but I would expect it should be a fairly quick way to resolve the issue.

Cheers,
Andrew

**Comment by awasson** [comment]
On further inspection, it looks to me like the problem was introduced when the jquery.instagramFeed was updated to inject the instagram caption text into the image alt tag. 

It's not necessarily a problem with the way this instagram user names his images. I think that is just a coincidence. It seems that the caption text on this particular image contains single and double quotes and as a result, that has broken the image tag in the feed. 

I think all that needs to be do is to sanitize the caption text before it is injected into the alt attribute then it wouldn't have the risk of breaking the image tag.

**Comment by jsanahuja** [comment]
It looks like the problem is the character ">" as long as we are not escaping the captions. 
Will fix it soon, thanks :)

**Comment by awasson** [comment]
That makes sense. Of course an unescaped ">" character would close the tag and everything else would be trashed. Yes, escaping the captions should fix it up. I'll keep an eye out for the next update.

Thanks,
Andrew
