### ISSUE TITLE
Just stopped working with username...

### ISSUE THREAD

**Issue by cesarielle** [jsanahuja/jquery.instagramFeed#53]
Hi,
Thanks for this nice project!
The function just stopped working when it used with username on my website.
I checked on your documentation website and it's same issue.
Do you know what happened?
Thanks for your help,
Kind regards

**Comment by mahotilo** [comment]
This might be due to too many requests from one IP. Obviously, you are banned for 24 hours. This happened to me too, when I was actively working on my site. You can check your page through some proxy. I am sure it will be OK.

**Comment by cesarielle** [comment]
Oh ok, thanks a lot for your reply! Hope tomorrow it will be fine :)
Kind regards,

**Comment by jsanahuja** [comment]
Exactly what @mahotilo said, you can find more info about this in #25
