### ISSUE TITLE
InstagramFeed Error

### ISSUE THREAD

**Issue by EricMarks** [jsanahuja/jquery.instagramFeed#54]
On the main demo page any of the instagram feeds using 'username' instead of 'tag' are receiving an error and not showing. On my websites using the instagram feed I am also getting an error and the feeds are not loading.

![image](https://user-images.githubusercontent.com/35350619/75815559-dd501000-5d50-11ea-8074-a87ce9ccd2e2.png)

**Comment by jsanahuja** [comment]
This is not a library issue. It is a temporary ban from Instagram because you have done too many requests. You can find a complete analysis of this in #25

**Comment by mahotilo** [comment]
Do you have an active Adblock? It can also cause this error.

**Comment by EricMarks** [comment]
yeah looks like the issue was we were making too many requests. Thank you for the quick responses!

**Comment by jsanahuja** [comment]
You're welcome :)
