### ISSUE TITLE
Video issue

### ISSUE THREAD

**Issue by qjhammer** [jsanahuja/jquery.instagramFeed#57]
If theres a video in the account the scripts crashes and stops working. Not even showing images from feed.

**Comment by jsanahuja** [comment]
I have tested with an account that the lastest 12 posts are videos and haven't found any issue. Can you please provide code examples and a screenshot?

**Comment by qjhammer** [comment]
I changed the the username in the demo. the Instagram account was business account. please try username flowmaticpk

**Comment by qjhammer** [comment]
Does this work with business accounts. Can anyone else replicate the error.

**Comment by jsanahuja** [comment]
I have replicated the error using the username you provided. The problem is that `imgs[i].node.accessibility_caption` is defined but null. Then throws an error while escaping the caption because we're trying to use `replace` on null.
This will be patched today

**Comment by jsanahuja** [comment]
Fixed in 1.2.3 release
