### ISSUE TITLE
How to make it work on Chrome?

### ISSUE THREAD

**Issue by danielmekis** [jsanahuja/jquery.instagramFeed#58]
Hello,

I have a little problem. Its working perfectly on Safari, however when I open the page on Chrome a nothing works.
<img width="336" alt="Screenshot 2020-04-02 at 18 56 52" src="https://user-images.githubusercontent.com/33416593/78276882-ebda4480-7513-11ea-84a7-bd22a7698fab.png">

**Comment by jsanahuja** [comment]
It works for me on Chrome. Do you see the same errors in https://www.sowecms.com/demos/jquery.instagramFeed?

**Comment by danielmekis** [comment]
Yes, similar:

**Comment by danielmekis** [comment]
Also yesterday it was perfect on Safari today it stopped working:
<img width="720" alt="Screenshot 2020-04-03 at 8 48 08" src="https://user-images.githubusercontent.com/33416593/78332345-25e52e00-7588-11ea-8357-2be9f435ef66.png">

**Comment by mahotilo** [comment]
It happened to me too, but disappeared a day later.

**Comment by jsanahuja** [comment]
> Also yesterday it was perfect on Safari today it stopped working:
> <img alt="Screenshot 2020-04-03 at 8 48 08" width="720" src="https://user-images.githubusercontent.com/33416593/78332345-25e52e00-7588-11ea-8357-2be9f435ef66.png">
> 
> I tried to print the JSON data what it get from instagram its undefined, maybe something was modified on insta, or am I doing something wrong?

This is not the same error. This is a network temporary ban from Instagram. See #54 #53 #51 #50 #49 #42 #25 (TLDR: See only #25 )

**Comment by mahotilo** [comment]
> This is a network temporary ban from Instagram. See #54 #53 #51 #50 #49 #42 #25 (TLDR: See only #25 )


@jsanahuja,
you should add this point to the script description to save your time.

**Comment by jsanahuja** [comment]
I definetely will @mahotilo 😄
