### ISSUE TITLE
CORS Policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by markfenske84** [jsanahuja/jquery.instagramFeed#6]
All our sites using this script have gone down with the same CORS error at same time. Instagram may have changed their CORS policy recently, as this script has been working perfectly for months.  Is there any way to get around the error?

`Access to XMLHttpRequest at 'https://www.instagram.com/ACCOUNTNAME' from origin 'https://SITE.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by jsanahuja** [comment]
You're right, they changed their CORS policy. I committed a workaround using an external service that seems to deal with this problem pretty well:

https://github.com/Rob--W/cors-anywhere

**Comment by LuisaGamez** [comment]
Thanks :-)

**Comment by jsanahuja** [comment]
FYI: Instagram seems to have changed their CORS policy again. Back to no proxy needed. I commited some changes, proxy functionality will be still available.
