### ISSUE TITLE
direct pictures id selection

### ISSUE THREAD

**Issue by flakesnow** [jsanahuja/jquery.instagramFeed#60]
hello at first thank you for this simple tool without needed api support. its greate

is there a simple way that I can tell the script when loading which pictures it should load explicitly? 
total pictures e.g. 20.  and it should load picture 1-4, and when i tell em picture 5-8, .... picture 9-12  ect. ect. without changing the script itself? or i have to use get data with callback and build it by my own?

thank you :)

**Comment by mahotilo** [comment]
> i have to use get data with callback and build it by my own?

Yes
