### ISSUE TITLE
It's working on some devices and not on others

### ISSUE THREAD

**Issue by gabrielamelo** [jsanahuja/jquery.instagramFeed#61]
Hello,
I've been using the plugin on my Blogger themes since February (i own a small Etsy shop), and recently, some people have told me it's not working, but I can still see the plugin on their pages. The same people also told me that they were asking someone else to check and that they were seeing it too. So, some people can see and others can't.
Is this a known situation? Any clues as to what it might be?
Thank you!

**Comment by mahotilo** [comment]
Try to check the end of this [pinned issue](https://github.com/jsanahuja/jquery.instagramFeed/issues/25).
Are you sure that these people didn't abuse reloading of your page with script?

**Comment by gabrielamelo** [comment]
i will look at it, thank you (:

**Comment by jsanahuja** [comment]
Probably had been refreshing the page a lot of times and got restricted by Instagram. As far as I know it takes a day or so to be able to do the requests again

**Comment by gabrielamelo** [comment]
gotcha, thank you!! :D
