### ISSUE TITLE
php variable and functin

### ISSUE THREAD

**Issue by Alexisback** [jsanahuja/jquery.instagramFeed#63]
I can insert a variable php into the function
which takes dynamic data for each field
example:
`$instagram=$row['urlinstagram'];
`

```
<script>
        (function($){
            $(window).on('load', function(){
                $.instagramFeed({
                    'username': '$instagram',
```

**Comment by jsanahuja** [comment]
Issues are not intended for technical support. Anyway the way you can do that is embedding PHP in your HTML/JS:
`'username': '<?php echo $instagram; ?>',`
