### ISSUE TITLE
Plugin Stopped Working

### ISSUE THREAD

**Issue by louiswalch** [jsanahuja/jquery.instagramFeed#64]
I noticed yesterday that my Instagram feed stopped working. Debugging it looks like the Ajax request is being redirected to a login page on IG. This is happening on more then one use using the script and they both have public feeds.

Any idea what's going on?

<img width="485" alt="Screen Shot 2020-05-21 at 4 17 01 PM" src="https://user-images.githubusercontent.com/286013/82602197-b8647f80-9b7e-11ea-9820-4886c974adcc.png">

<img width="1190" alt="Screen Shot 2020-05-21 at 4 19 08 PM" src="https://user-images.githubusercontent.com/286013/82602282-d5994e00-9b7e-11ea-86eb-2a5b066dafa5.png">

**Comment by jsanahuja** [comment]
This is related to #25 which is an Instagram temporary network restriction. Also update to the lastest version which detects this.

**Comment by josep11** [comment]
It stopped working for me too. I switched from Wifi to data network so that the request count by IP was clear and it was still blocking the requests (redirecting to login)

**Comment by mahotilo** [comment]
For clear IP try to use VPN. Your Wi-fi and Ethernet could actually have the same IP

**Comment by josep11** [comment]
> For clear IP try to use VPN. Your Wi-fi and Ethernet could actually have the same IP

Hi my friend, I can confirm that the problem persists after using VPN from 3 different countries.

**Comment by mahotilo** [comment]
Hm. Let us wait for 24 hours. For me, script is working fine now.

**Comment by blueboo42** [comment]
Hi, I am having this same issue as well. I am assuming I just made too many requests as I was making revision after revision and CTRL+R-ing my page. Instagram is mad at me, lol. 

Will update after 24 hours or so and see if the issue clears up on its own. Love your work on this plugin, I think it is great and hope it works itself out. :)

**Comment by josep11** [comment]
Hello everyone, I can attest that after 48+ hours I tested with 2+ VPNs and my regular connection and the result is the same as before:

> Instagram Feed: It looks like YOUR network has been temporary banned because of too many requests.

**Comment by mahotilo** [comment]
What about demo site? Does it work for you?

**Comment by josep11** [comment]
Nope, it does not work and I have an important piece of information to share with you. The first 4 sites that show up on Google if you want to download a video from Instagram have problems at the moment. So I think IG changed a policy because they all redirect to /login.
The 4 sites are:

- https://www.w3toys.com/
- https://downloadgram.com/
- https://downloadinstagramvideos.net/
- https://instadownloader.co/instagram.php

**Comment by mahotilo** [comment]
Ok.
But at the moment, all (actually 2) of my sites with this great script are working fine. Maybe this is a regional restriction or a regional rollout of new rules.

**Comment by josep11** [comment]
> Ok.
> But at the moment, all (actually 2) of my sites with this great script are working fine. Maybe this is a regional restriction or a regional rollout of new rules. And maybe soon all of as will face such a problem. Will see...

Can you tell me which countries are you sending the requests from?
I am in Vietnam and it is not working. VPN from Poland, Netherlands and UK neither.

**Comment by mahotilo** [comment]
Ukraine. 
But I have just found that Opera VPNs from all regions have stopped work for me too.

**Comment by blueboo42** [comment]
The demo site site not working for me either. I am in the United States.

**Comment by jsanahuja** [comment]
It is working for me. I believe this is just a network ban from Instagram

**Comment by blueboo42** [comment]
Update: it is working again for me as well. Must have been a network ban from Instagram as many above suggested. Thank you!

**Comment by josep11** [comment]
Still the same issue here after one week without trying so I don't know what to do.

**Comment by mahotilo** [comment]
My current state.
Flawless work of this script on the real sites through direct access and ban through VPNs.
And all my other free IG scripts from third-party providers are dead.
I think IG changed the rules of the game.
