### ISSUE TITLE
 temporary banned because of too many request

### ISSUE THREAD

**Issue by renatoniola** [jsanahuja/jquery.instagramFeed#65]
I 'm getting this error , anyone knows how to fix it?
'Instagram Feed: It looks like YOUR network has been temporary banned because of too many request'

thanx

**Comment by mahotilo** [comment]
It means exactly what it says. Wait 24 hours and avoid too many reloading of your page with script.

**Comment by renatoniola** [comment]
then it might be not the library for me , I need to work all the time.

**Comment by jsanahuja** [comment]
The ban is just for you, not for everybody. You probably have been refreshing the page many times

**Comment by renatoniola** [comment]
ah that makes sense , yep I'm testing it cause I'm building a website. So I guess it should work for most people , thanx.
