### ISSUE TITLE
For how much user we can use this jquery.

### ISSUE THREAD

**Issue by virendrapacemaker** [jsanahuja/jquery.instagramFeed#67]
Hello Team,

Thanks for this jQuery plugin. It works very good!

I have used this plugin on my website. There is more than 2000 instagram plugin. So we are using this plugin to show instagram feed when click on username. We have list of user, when click on username its open a popup and at bottom of popup we are using your script for show instagram feed ofr that particular user.

I just wnat to know that for how much user we can access this jQuery. Is there any limitation with this jquery that we can access this for limited no. of user in an hour? Please see screenshot of my list user.
 
![Screenshot from 2020-06-11 13-18-35](https://user-images.githubusercontent.com/1033119/84359637-8cb94000-abe6-11ea-94f7-dfacdec0bf45.png)

Thanks

**Comment by jsanahuja** [comment]
There are network limitations but them all are from Instagram. As long as this plugin is client-side, this limitation is for the client that is opening the popups, not for everyone. 

If you do a lot of requests your network will be banned and the plugin will stop working for a while. It usually takes a day to be able to make more requests

**Comment by virendrapacemaker** [comment]
Thanks for reply. Do you have any jquery to get follower of instagram. I was using https://www.instagram.com/carolinesimpsonn/?__a=1 where carolinesimpsonn is instagram username. but this api block for my site. Can you suggest me any other api that return instagram follower without token like your feed jquery.

**Comment by jsanahuja** [comment]
If you mean the follower count, you can get it with this plugin using the callback feature. The field name is `edge_followed_by`. See the example 7 in the docs. 
If you are willing to get the list of followers I don't think you can do that without authentication.

IMO this plugin is not what fits your use case at all. I would make a cron-based script in the backend that periodically (probably daily and waiting between users) imports all that data so you would be able to get it anytime without worring about being banned from Instagram.

**Comment by virendrapacemaker** [comment]
Thank you.

I found follower count using jquery and that is fine. But I want follower count value in php code. I have a cron that update follower count in database. previously I am doing that with file_get_content(https://www.instagram.com/carolinesimpsonn/?__a=1). Do you have any idea how can I get this in php code?

**Comment by jsanahuja** [comment]
You can do the same this library does, just take a look at the code

**Comment by virendrapacemaker** [comment]
I have checked but not getting code to use in php or an url of api.

**Comment by jsanahuja** [comment]
As I told you, you can do the same this library does but in PHP. Read the code, understand it and write it in PHP. Im closing this as it is not an issue nor related to this library
