### ISSUE TITLE
Use of inefficient and unsupported data retrieval method

### ISSUE THREAD

**Issue by bartvanraaij** [jsanahuja/jquery.instagramFeed#76]
I've taken a look at how this utility fetches data from Instagram.
It loads the entire http response of an Instagram url (e.g. a profile page, https://www.instagram.com/instagram/) with a [jQuery.get XMLHttpRequest](https://github.com/jsanahuja/jquery.instagramFeed/blob/master/jquery.instagramFeed.js#L69-L71) and subsequently parses the html response to find the global [`window._sharedData`](https://github.com/jsanahuja/jquery.instagramFeed/blob/master/jquery.instagramFeed.js#L73) variable to extract all data that is needed to display the feed.

I must say this a very clever find!

However... there's two problems with this method:

1. It's inefficient:
The user's browser needs to download the entire http html response of (for example) a user's profile page, where only the "json" data in `window._sharedData` is needed.
A small sample of requests show that loading time is anywhere between 800ms and 1200ms. That's quite significant I'd say.

2. It's totally unsupported
The `window._sharedData` variable is clearly an internally used variable by Instagram. It's not documented anywhere publicly. It's obviously not supposed to be used by third parties.
Therefore there's absolutely no indication whatsoever that this will continue to work. 
Instagram may choose to alter the variable name or its structure or choose to remove it at any given time. Or they may choose to add CORS-headers to these requests which will break this utility, because the browser won't perform the http request anymore.

That's not to say that one shouldn't use this utility. 
But I do think a few warnings are in order. 
Maybe you can add a warning to the projects [Readme](https://github.com/jsanahuja/jquery.instagramFeed/blob/master/README.md), for example:

## Warning: long term operation not guaranteed
This utility uses an unconventional method to retrieve data from Instagram which is officially not supported by Instagram. Instagram may alter its internal workings at any given time, which may cause this utility to stop functioning. Long term operation can therefore not be guaranteed.

**Comment by jsanahuja** [comment]
The complete HTTP request is about 40kB. Of course we do not need the entire HTML response but we can't fetch just the JSON unless we use their access-token-based API. When you use Bootstrap or jQuery you are also fetching code you don't need. If you think you can improve the efficiency you can send a pull request.

I think it is obvious this library uses an unconventional method to retrieve the data. The only supported method is the Instagram API and as I have stated several times this repository's purpose is diametrically opposed to its use.

**Comment by bartvanraaij** [comment]
> I think it is obvious this library uses an unconventional method to retrieve the data.
How is this obvious? You need to look at the source code to figure that out.
I think it'd be helpful for people to point this out in the project's readme.

> The only supported method is the Instagram API 
You know that, I know that, but not every developer may know that. They'll read "Instagram feed without the API" and think: "Hey, that's cool, I can use that!". And be frustrated in a few months when this will stop working, hypothetically (might me days, might be years, might be never, you don't know).

>and as I have stated several times this repository's purpose is diametrically opposed to its use.
I imagine that you've pointed this out in earlier issues. But a developer looking to use this product will probably only look at the Readme.

I'm not pushing hard on this. I think you've come up with a very clever solution to the "Instagram API Key"-problem. So thanks for that!
I'm just saying that it could be helpful to add an explanation or warning to users that this tool may break at any point in time.
This will also prevent you from having to answer multiple issue when that time comes - as you would've made it clear that no guaranteed operation is to be expected.

But in the end it's your repo, your product, your call :-).

Thanks for answering.
