### ISSUE TITLE
On VPN  i am not able to view Instagram gallery 

### ISSUE THREAD

**Issue by muhammadsarfraz6** [jsanahuja/jquery.instagramFeed#78]
Hello , 
On VPN  i am not able to view Instagram gallery and on console i am getting error message "InstagramFeed: It looks like YOUR network has been temporary banned because of too many requests. See https://github.com/jsanahuja/jquery.instagramFeed/issues/25 " 

can you please let me know about it. 

Bright regards,
MS

**Comment by jsanahuja** [comment]
The message is self explaining. Your network (your VPN network in this case) has been temporary banned because of too many requests. See #25 or any of all the other issues about this

**Comment by muhammadsarfraz6** [comment]
Okay Many thanks for your reply , Can you please let me know how many request we can send in a day ? because still 24 hours passed its still not working and i am not able to see the insta gallery on page .
