### ISSUE TITLE
I can't get it to work anymore :(

### ISSUE THREAD

**Issue by fabricioventura** [jsanahuja/jquery.instagramFeed#81]
I used it on some sites, but now when I try to implement it doesn't work on new sites, follow the warnings on inspect:

Access to XMLHttpRequest at 'https://www.instagram.com/boxfuncional/' from origin 'https://www.boxfuncional.com' has been blocked by CORS policy: Request header field x-csrf-token is not allowed by Access-Control-Allow-Headers in preflight response.

jquery.instagramFeed.min.js: 195 Instagram Feed: Unable to fetch the given user / tag. Instagram responded with the status code: 0 5
(anonymous) @ jquery.instagramFeed.min.js: 195

www.instagram.com/boxfuncional/:1 Failed to load resource: net :: ERR_FAILED

Any help getting it working again? Thanks!

**Comment by fabricioventura** [comment]
Using only Instagramfeed, I had this other error code:

Uncaught TypeError: Cannot set property 'innerHTML' of null
    at Object.display (InstagramFeed.min.js:237)
    at InstagramFeed.min.js:243
    at XMLHttpRequest.xhr.onload (InstagramFeed.min.js:103)

**Comment by jsanahuja** [comment]
You `$.ajax` is sending a `X-CSRF-Token` header so you are probably doing something like this:
```
$.ajaxSetup({
    beforeSend: function (xhr)
    {
       xhr.setRequestHeader("X-CSFR-Token","...");
    }
});
```
That breaks the library as Instagram does not accept that header.

**Comment by fabricioventura** [comment]
> Você `$.ajax`está enviando um `X-CSRF-Token`cabeçalho, então provavelmente está fazendo algo assim:
> 
> ```
> $.ajaxSetup({
>     beforeSend: function (xhr)
>     {
>        xhr.setRequestHeader("X-CSFR-Token","...");
>     }
> });
> ```
> 
> Isso quebra a biblioteca, pois o Instagram não aceita esse cabeçalho.

How do I block this? I'm using a Joomla cms, how can I find out who is sending the header?

**Comment by csanahuja** [comment]
CTRL+F `ajaxSetup` in [view-source:https://www.boxfuncional.com](view-source:https://www.boxfuncional.com)

You can see the ajaxSetup there... if you remove it you may be breaking other CSRF protected requests. You need to figure out a solution that works for you
