### ISSUE TITLE
Add loading indicator

### ISSUE THREAD

**Issue by amichel86** [jsanahuja/jquery.instagramFeed#83]
Hello, thank you so much for your plugin, it came at the perfect time for my project! I had a quick question, is there a way to add a loading indicator (gif, svg, css that I'll be doing) when the pictures are loading, thanks! :)

**Comment by jsanahuja** [comment]
Do you mean a loading indicator for the rendering section or for each image while loading?

**Comment by amichel86** [comment]
Hey @jsanahuja, I just wanna put like a loading SVG to indicate the section is loading while the plugin grabs the images. Possible?

**Comment by jsanahuja** [comment]
Yes, you could put the SVG in the `container` and the plugin would remove it

**Comment by amichel86** [comment]
That easy? Awesome, will try it out :D
