### ISSUE TITLE
Not working Instagram Feeed

### ISSUE THREAD

**Issue by mohinpatwary** [jsanahuja/jquery.instagramFeed#84]
It looks like YOUR network has been temporary banned because of too many requests.

![image](https://user-images.githubusercontent.com/24967072/95061793-e4dbfb00-071d-11eb-8911-72e8ce0af571.png)

How can I fix this issue?

Please help

**Comment by mahotilo** [comment]
Just wait at least 24 hours.

**Comment by phuocCVA** [comment]
hi, i have waited for 3 days and the issue still there

Please help

**Comment by mahotilo** [comment]
It is Ok here. Could you check on from a different IP?

**Comment by phuocCVA** [comment]
Yeah, already checked from a different network and a different computer but still have the issue

**Comment by mahotilo** [comment]
What about [demo](https://www.sowecms.com/demos/jquery.instagramFeed/index.html), does it work for you?

**Comment by phuocCVA** [comment]
No, it doesn't, i see only the code and also have the issue in the console

**Comment by mahotilo** [comment]
Are you using any public VPN, Proxy?

**Comment by phuocCVA** [comment]
no, none of them :(

**Comment by mahotilo** [comment]
I give up. It should work unless Instagram have any special complaints about your location, provider etc.

**Comment by phuocCVA** [comment]
ok, thanks :(

**Comment by jsanahuja** [comment]
@phuocCVA could you please check your network tab and provide a pastebin with the response from instagram?

Or tell us what happens when you access for example this url with your browser (better through incognito mode): https://www.instagram.com/instagram/

**Comment by ngoclx** [comment]
Hi jsanahuja,

It requires login by redirecting me to this page https://www.instagram.com/accounts/login/?next=/instagram/

**Comment by ngoclx** [comment]
The response to the library's request also asks for logging-in.
entry_data > LoginAndSignupPage

**Comment by jsanahuja** [comment]
Something between you and IG, nothing we can do
