### ISSUE TITLE
Documentation Unclear

### ISSUE THREAD

**Issue by tdw46** [jsanahuja/jquery.instagramFeed#86]
I've entered the code as follows on the[ Tryit Editor from W3Schools](https://www.w3schools.com/tryit/tryit.asp?filename=tryhtml_default) with no success:

<div id="instagram-feed1" class="instagram_feed1"></div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://raw.githubusercontent.com/jsanahuja/jquery.instagramFeed/master/jquery.instagramFeed.min.js"></script>
<script>
    (function($){
        $(window).on('load', function(){
            $.instagramFeed({
                'username': 'pyperbleucollective',
                'container': "#instagram-feed1",
                'display_profile': true,
                'display_biography': true,
                'display_gallery': true,
                'callback': null,
                'styling': true,
                'items': 8,
                'items_per_row': 4,
                'margin': 1,
                'lazy_load': true,
                'on_error': console.error
            });
        });
    })(jQuery);
</script>

I've also tried adding the same code to a custom HTML widget on my shopify website to no avail. I'm sure I'm missing something here that I am unaware of as a newb to web dev. Can you please clarify what my error is? Thank you.

**Comment by mahotilo** [comment]
Try to use this address
`https://cdnjs.cloudflare.com/ajax/libs/jquery.instagramFeed/1.3.2/jquery.instagramFeed.min.js`

and I hope you have defined in code smth like 
`<div id=''instagram-feed1"></div>`

**Comment by tdw46** [comment]
That worked like a charm! Thanks, I had a feeling it had to do with the script path.
