### ISSUE TITLE
"Tags" Option No Longer Working

### ISSUE THREAD

**Issue by kferencz91** [jsanahuja/jquery.instagramFeed#90]
It appears that the option to pull by tag no longer appears to be working properly. Even the demo site appears to be experiencing this issue: https://www.sowecms.com/demos/jquery.instagramFeed/index.html (example 4). The profile seems to load, but any line items underneath the tag do not. Console logs don't indicate any errors. This has been tested using multiple IP addresses, so I don't think it has anything to do with a block on IG's end, especially since all other examples seem to be rendering as expected. 

<img width="1211" alt="Screen Shot 2020-11-17 at 6 52 11 PM" src="https://user-images.githubusercontent.com/18629607/99464398-07108d80-2906-11eb-84f6-af5889f0eb89.png">

**Comment by jsanahuja** [comment]
It is working for me. Please check if you see any error in console.

**Comment by kferencz91** [comment]
No console errors, unfortunately.

Have tested on MacOS using Safari, Firefox and Chrome on multiple IPs, Chrome for PC on multiple IPs, and Safari for iOS on both static wifi IP and variable LTE IP. All other examples on the demo page work and load as expected, but the tags-based one - Example 4 - only loads the profile and nothing else.

**Comment by jsanahuja** [comment]
I just tested in Chrome, Firefox, Edge and Opera and it is working. Please ensure you have no filters in your browser's console:
![2020-11-18 15_20_28-jquery instagramFeed](https://user-images.githubusercontent.com/16489902/99542062-e4d44980-29b1-11eb-869b-51a3b1d8726e.png)
