### ISSUE TITLE
Cross-origin request on Firefox !

### ISSUE THREAD

**Issue by frogerfred** [jsanahuja/jquery.instagramFeed#91]
Hello, 
I'm using this fabulous add-on since a year now ! Thanks again for your work ! 

Today i have a problem too complicated for me to solve. 
I can't get access to any instagram content from my website when i'm using firefox. 

The website is on wordpress, https://les-artistes-tatoueurs.fr. 
No problem with Chrome. 
![CORS](https://user-images.githubusercontent.com/31008697/99549338-d38f3b00-29b9-11eb-8581-915c90c38d3e.jpg)

As you can see, firefox blocks the request to instagram. 

If someone have time to explain me what can i do, thanks, can't find a solution easy to understand for my low level in programing.

Have a good day.

**Comment by raphaelApard** [comment]
Hello,

Do you use plugin like AdBlock ?

**Comment by frogerfred** [comment]
Hi, 
Thanks for replying. 
Adblock is disable when on this website so... I checked my other plugins ! 
The problem is : Facebook Container ! i disabled it and, wow, it works ! 

Sorry for bothering you, i forgot that Instagram and facebook are in the same boat now. 

Thanks thanks thanks !
