### ISSUE TITLE
Stretched images by height

### ISSUE THREAD

**Issue by Saaskoo** [jsanahuja/jquery.instagramFeed#92]
Hi, 

I found some issue on desktop Safari and mobile Chrome and Safari.
Tested on iOS 14.1, and updated browsers on latest version.

![mobile](https://user-images.githubusercontent.com/74592532/99633686-99687c80-2a3f-11eb-8b3f-e475d5cd9a75.jpg)

![desktop](https://user-images.githubusercontent.com/74592532/99633472-45f62e80-2a3f-11eb-9f2c-3b2921a27bd2.jpg)

Otherwise, thumbs up for a great script :)

**Comment by jsanahuja** [comment]
I just made a small change. Could you please try again?

**Comment by Saaskoo** [comment]
Tested and works great 👍 

Thanks for fast support!

**Comment by jsanahuja** [comment]
Thank you :)
