### ISSUE TITLE
Library stopped working

### ISSUE THREAD

**Issue by joeforjoomla** [jsanahuja/jquery.instagramFeed#94]
It seems that Instagram feeds are no more publicly available, as a result this scraper does not work anymore. 
The Instagram page is always redirected to the login page.

**Comment by jsanahuja** [comment]
It does work for me
![image](https://user-images.githubusercontent.com/16489902/100471849-6a0add00-30db-11eb-94e9-16966264529b.png)

Your network is probably temporary banned (See #25)

**Comment by joeforjoomla** [comment]
I don't think, logout and clear all cookies. Then try to open the account page: 
https://www.instagram.com/pascal_belhomme/
You will get redirected to the login page.

**Comment by joeforjoomla** [comment]
Probably you have cookies and figure still logged in to Instagram. Ensure to have logged out and cleared all cookies. The login page is always redirected

**Comment by joeforjoomla** [comment]
Related to #25

**Comment by jsanahuja** [comment]
The first screenshot was in incognito mode. Tried again and the same:

![image](https://user-images.githubusercontent.com/16489902/100476550-249fdd00-30e6-11eb-8236-12aa01fe932e.png)

**Comment by joeforjoomla** [comment]
@jsanahuja do some more tests to understand what's happening because all my tests changing IP address, browser, etc lead always to the same result when i open https://www.instagram.com/pascal_belhomme/, that is the Instagram login page

![image](https://user-images.githubusercontent.com/17835460/100478426-75660480-30eb-11eb-904d-54e0987e77b3.png)

**Comment by joeforjoomla** [comment]
You can also test my demo site, 302 redirect to login:

![image](https://user-images.githubusercontent.com/17835460/100478480-96c6f080-30eb-11eb-8947-fc79171320d0.png)

**Comment by joeforjoomla** [comment]
I think related to: https://www.reddit.com/r/uBlockOrigin/comments/jz5o3f/instagram_links_redirect_to_login_page_anyway_to/

**Comment by jsanahuja** [comment]
The new client-side caching (`cache_time`) feature implemented in #97 (2.0.0 release) should deal with this.
