### ISSUE TITLE
mySql version?

### ISSUE THREAD

**Issue by GetASiteSe** [jsanahuja/jquery.instagramFeed#96]
Is there any chance to get a version of this amazing script with a tweek that instead of printing out the result of the code in  the website, it stores the information in a mysql database?

With this kind of tweek the user can call the script with a cronjob once every hour and by that way avoid the IP-ban from Instagram because of to many request.

**Comment by mgrn0** [comment]
imho this would be something that does not belong in this js library because it heavily depends 
* on the type/version of database you are using
* the serverside scripting language you are using (php, java, ...)
and does not belong to the client side of a web application..

**Comment by jsanahuja** [comment]
Exactly what @mgrn0 said. An alternative to this is client-side caching using `localStorage` implemented in #97. It will be ready in the 2.0.0 release
